[package]
name = "indi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = {version="~0.26.0", features=["encoding", "async-tokio"]}
chrono = "0.4"
encoding = "0.2"
base64 = "0.13.0"
log = "0.4.17"
derivative = "2.2.0"

[dev-dependencies]
bytes = "1.2.1"

